message(STATUS "")
message(STATUS "Transmit ${PROJECT_VERSION} configuration")
message(STATUS "  build type ......... ${CMAKE_BUILD_TYPE}")
message(STATUS "  desktop app ........ ${TRANSMIT_BUILD_APP}")
message(STATUS "  cli ................ ${TRANSMIT_BUILD_CLI}")
message(STATUS "  tests .............. ${TRANSMIT_BUILD_TESTS}")
message(STATUS "  zstd ............... ${TRANSMIT_ZSTD_SOURCE}")
message(STATUS "  liblzma (xz) ....... ${TRANSMIT_LZMA_ENABLED} (${TRANSMIT_LZMA_SOURCE})")
message(STATUS "  OpenSSL (crypto) ... ${TRANSMIT_OPENSSL_ENABLED} (${TRANSMIT_OPENSSL_SOURCE})")
message(STATUS "  SQLite3 ............ ${TRANSMIT_SQLITE_SOURCE}")
if(TRANSMIT_BUILD_APP OR TRANSMIT_BUILD_TESTS)
    message(STATUS "  Qt ................. ${Qt6_VERSION}")
endif()
message(STATUS "")
